# .github/workflows/docker-publish.yml

name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ] # Executa quando houver push na branch main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Permissão para enviar pacotes (imagens)

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to the GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./Sitepronto # Informa que o Dockerfile está na pasta Sitepronto
        push: true
        tags: ghcr.io/murilonicioli/intus-ai:latest # IMPORTANTE: use seu usuário/nome do repo aqui
