# .github/workflows/docker-publish.yml (VERSÃO CORRIGIDA)

name: Build and Push Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Log in to the GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    # ESTE NOVO PASSO CONVERTE O NOME DE USUÁRIO PARA MINÚSCULAS
    - name: Prepare image tags
      id: prep
      run: |
        OWNER_LC=$(echo "${{ github.repository_owner }}" | tr '[:upper:]' '[:lower:]')
        echo "OWNER_LC=$OWNER_LC" >> $GITHUB_OUTPUT

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ./Sitepronto
        push: true
        # A tag agora usa a versão em minúsculas do seu nome
        tags: ghcr.io/${{ steps.prep.outputs.OWNER_LC }}/intus-ai:latest