# docker-compose.yml (MODO DE TESTE FINAL)

version: '3.8'

services:
  intusai-site:
    image: intusai-site-teste:latest # Usando um novo nome de imagem para evitar cache
    build:
      context: ./Sitepronto
      dockerfile: Dockerfile
    
    # Expondo uma porta diretamente para o teste, ignorando Traefik.
    # Usamos uma porta alta (8081) para não ter conflito.
    ports:
      - "8081:80"

    deploy:
      mode: replicated
      replicas: 1
      # Nenhuma label do Traefik.
      # Nenhuma restrição de placement.
      # Apenas o mínimo absoluto para rodar.