version: '3.8'

services:
  intusai-site:
    image: intusai-site:${TAG:-latest}
    build:
      context: ./Sitepronto
      dockerfile: Dockerfile
    networks:
      - intusai-net-desenv
    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        
        # Roteador HTTP simples (será redirecionado globalmente pelo Traefik)
        - "traefik.http.routers.intusai-site-http.rule=Host(`intusai.com.br`)"
        - "traefik.http.routers.intusai-site-http.entrypoints=web"

        # Roteador principal para HTTPS
        - "traefik.http.routers.intusai-site-https.rule=Host(`intusai.com.br`)"
        - "traefik.http.routers.intusai-site-https.entrypoints=websecure"
        - "traefik.http.routers.intusai-site-https.tls=true"
        # CORREÇÃO: Usando o nome exato do seu resolvedor de certificados
        - "traefik.http.routers.intusai-site-https.tls.certresolver=letsencryptresolver"

        # Serviço que o Traefik vai usar
        - "traefik.http.services.intusai-site-service.loadbalancer.server.port=80"

networks:
  intusai-net-desenv:
    external: true