version: '3.8'

services:
  intusai-site:
    # Usando a imagem pronta que o GitHub Actions criou
    image: ghcr.io/murilonicioli/intus-ai:latest

    # Ao publicar uma porta, o Swarm automaticamente usará a rede 'ingress'
    ports:
      - "8082:80"

    deploy:
      mode: replicated
      replicas: 1