# docker-compose.yml (Versão Final para Deploy Manual)
version: '3.8'

services:
  intusai-site:
    # Nome da imagem a ser construída. Será local no seu servidor.
    image: intusai-site:latest
    build:
      # Caminho absoluto para a pasta com o código na sua VPS
      context: /root/stacks/intus-ai/Sitepronto
      dockerfile: Dockerfile
    
    networks:
      - intusai-net-desenv

    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.intusai-site-http.rule=Host(`intusai.com.br`)"
        - "traefik.http.routers.intusai-site-http.entrypoints=web"
        - "traefik.http.routers.intusai-site-https.rule=Host(`intusai.com.br`)"
        - "traefik.http.routers.intusai-site-https.entrypoints=websecure"
        - "traefik.http.routers.intusai-site-https.tls=true"
        - "traefik.http.routers.intusai-site-https.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.intusai-site-service.loadbalancer.server.port=80"

networks:
  intusai-net-desenv:
    external: true