# docker-compose.yml (Coloque na RAIZ do seu repositório)

version: '3.8'

services:
  # O nome foi padronizado, mas você pode usar 'intusai-web' se preferir
  intusai-site:
    image: intusai-site:${TAG:-latest}
    build:
      # A instrução que adapta seu fluxo antigo para o novo
      context: ./Sitepronto
      dockerfile: Dockerfile
    
    networks:
      # O nome da sua rede foi corrigido aqui
      - intusai-net-desenv

    deploy:
      mode: replicated
      replicas: 1
      # A seção 'placement' foi removida para garantir o deploy
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.intusai-site-http.rule=Host(`intusai.com.br`)"
        - "traefik.http.routers.intusai-site-http.entrypoints=web"
        - "traefik.http.routers.intusai-site-http.middlewares=redirect-to-https"

        - "traefik.http.routers.intusai-site-https.rule=Host(`intusai.com.br`)"
        - "traefik.http.routers.intusai-site-https.entrypoints=websecure"
        - "traefik.http.routers.intusai-site-https.tls=true"
        - "traefik.http.routers.intusai-site-https.tls.certresolver=cloudflare"

        - "traefik.http.services.intusai-site-service.loadbalancer.server.port=80"

networks:
  intusai-net-desenv:
    external: true