# docker-compose.yml (VERSÃO FINAL E CORRETA)
version: '3.8'

services:
  intus-ai-site:
    # CORREÇÃO FINAL: Usando o caminho todo em minúsculas,
    # que agora corresponde ao que o GitHub Actions vai criar.
    image: ghcr.io/murilonicioli/intus-ai:latest

    networks:
      - intusai-net-desenv

    deploy:
      mode: replicated
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.intusai-site-http.rule=Host(`intus-ai.com.br`)"
        - "traefik.http.routers.intusai-site-http.entrypoints=web"
        - "traefik.http.routers.intusai-site-https.rule=Host(`intus-ai.com.br`)"
        - "traefik.http.routers.intusai-site-https.entrypoints=websecure"
        - "traefik.http.routers.intusai-site-https.tls=true"
        - "traefik.http.routers.intusai-site-https.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.intusai-site-service.loadbalancer.server.port=80"

networks:
  intusai-net-desenv:
    external: true